### ISSUE TITLE
Đề xuất thay đổi cấu trúc Blog 

### ISSUE THREAD

**Issue by haduytuan** [Rolbackse/blog-kanayomi#3]
Link bản Word.Xin mời mọi người tải về đọc 
[Đề xuất thay đổi giao diện KANAYOMI.docx](https://github.com/Rolbackse/blog-kanayomi/files/2117568/D.xu.t.thay.d.i.giao.di.n.KANAYOMI.docx)

**Comment by haha3170** [comment]
done
